# frozen_string_literal: true

source 'https://rubygems.org'

# Development and Testing
group :development, :test do
  gem 'rake', '~> 13.2'
  gem 'rubocop', '~> 1.68', require: false
  gem 'rubocop-performance', '~> 1.22', require: false
  gem 'rubocop-rake', '~> 0.6.0'
  gem 'rubocop-rspec', '~> 3.2'
end

# Testing
group :test do
  gem 'rspec', '~> 3.10'
  gem 'simplecov', '~> 0.22.0', require: false
end

gem 'can_messenger', '~> 0.1.0'
