# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem "ostruct", "~> 0.6.0"
gem "rake", "~> 13.2"

group :test do
  gem 'rspec', '~> 3.13'
  gem "simplecov", "~> 0.22.0"
end
